# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  servers = [
    {
      name: "web-server",
      memory: 1024,
      cpus: 1
    },
    {
      name: "app-server",
      memory: 1024,
      cpus: 1
    },
    {
      name: "db-server",
      memory: 1024,
      cpus: 1
    },
    {
      name: "monitoring-server",
      memory: 2048,
      cpus: 2
    }
  ]

  servers.each do |server|
    config.vm.define server[:name] do |node|
      node.vm.hostname = server[:name]

      # Parallels-Konfiguration
      node.vm.provider "parallels" do |prl|
        prl.name = server[:name]
        prl.memory = server[:memory]
        prl.cpus = server[:cpus]
      end

      # VirtualBox-Konfiguration
      node.vm.provider "virtualbox" do |vb|
        vb.name = server[:name]
        vb.memory = server[:memory]
        vb.cpus = server[:cpus]
      end

      # VMware Fusion / Workstation
      node.vm.provider "vmware_desktop" do |vmware|
        vmware.vmx["displayName"] = server[:name]
        vmware.vmx["memsize"] = server[:memory].to_s
        vmware.vmx["numvcpus"] = server[:cpus].to_s
      end
    end
  end
end