[web]
web-server ansible_host=10.211.55.35 ansible_ssh_private_key_file=../vagrant/.vagrant/machines/web-server/parallels/private_key

[app]
app-server ansible_host=10.211.55.33 ansible_ssh_private_key_file=../vagrant/.vagrant/machines/app-server/parallels/private_key

[db]
db-server ansible_host=10.211.55.34 ansible_ssh_private_key_file=../vagrant/.vagrant/machines/db-server/parallels/private_key

[monitoring]
monitoring-server ansible_host=10.211.55.32 ansible_ssh_private_key_file=../vagrant/.vagrant/machines/monitoring-server/parallels/private_key

[all:vars]
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'