[web]
web-server ansible_host=10.211.55.44 ansible_ssh_private_key_file=/Users/romag/Documents/teko/netzwerk/Ansible-based-Server-Monitoring-Deployment/vagrant/.vagrant/machines/web-server/parallels/private_key

[app]
app-server ansible_host=10.211.55.42 ansible_ssh_private_key_file=/Users/romag/Documents/teko/netzwerk/Ansible-based-Server-Monitoring-Deployment/vagrant/.vagrant/machines/app-server/parallels/private_key

[db]
db-server ansible_host=10.211.55.41 ansible_ssh_private_key_file=/Users/romag/Documents/teko/netzwerk/Ansible-based-Server-Monitoring-Deployment/vagrant/.vagrant/machines/db-server/parallels/private_key

[monitoring]
monitoring-server ansible_host=10.211.55.43 ansible_ssh_private_key_file=/Users/romag/Documents/teko/netzwerk/Ansible-based-Server-Monitoring-Deployment/vagrant/.vagrant/machines/monitoring-server/parallels/private_key

[all:vars]
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
