---
app_name: ansible-monitoring-app
app_user: appuser
app_group: appuser
app_dir: /opt/ansible-monitoring-app
app_port: 5000

app_host: "10.211.55.33"

app_db_host: "10.211.55.34"
app_db_name: appdb
app_db_user: appuser
app_db_password: apppassword

web_server_ip: "10.211.55.35"
app_server_ip: "10.211.55.33"
db_server_ip: "10.211.55.34"
monitoring_server_ip: "10.211.55.32"